version: "3.9"

services:
  waifu_bot:
    build:
      context: ./Domination-BOT-node
      dockerfile: Dockerfile
    container_name: waifu_bot
    restart: always
    env_file:
      - .env
    environment:
      TYPE_BOT: waifu

  husbando_bot:
    build:
      context: ./Domination-BOT-node
      dockerfile: Dockerfile
    container_name: husbando_bot
    restart: always
    env_file:
      - .env
    environment:
      TYPE_BOT: husbando

  web:
    build:
      context: ./domination-bot-web
      dockerfile: Dockerfile
    container_name: web
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env