"""criação inicial

Revision ID: 0902a6360a78
Revises: 
Create Date: 2025-08-31 09:53:29.998132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0902a6360a78'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('E_EVENTOS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('COD', sa.Enum('SEM_EVENTO', 'HALLOWEEN', 'PRIMAVERA', 'VERAO', 'INVERNO', 'OUTONO', 'ANO_NOVO', 'NATAL', 'VALENTINA', 'INFANTIL', 'COELHINHA', 'CARNAVAL', 'EMPREGADA', 'ANJO', 'ESPORTIVO', 'KIMONO', 'GALA', 'GALA_MASCULINA', 'ANO_NOVO_LUNAR', 'ENFERMEIRA', 'ESCOLAR', 'GAME', name='tipoevento'), nullable=False),
    sa.Column('nome_traduzido', sa.String(length=100), nullable=True),
    sa.Column('emoji', sa.String(length=5), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('COD')
    )
    op.create_table('E_RARIDADE',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('COD', sa.Enum('COMUM', 'INCOMUM', 'RARO', 'LENDARIO', 'EXCLUSIVO', 'LIMITADO', 'ESPECIAL', 'MULTIVERSO', 'ESPECTRAL', name='tiporaridade'), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('emoji', sa.String(length=5), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('COD')
    )
    op.create_table('USUARIOS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('telegram_from_user', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('perfil_status', sa.Enum('SUPREMO', 'SUPER_ADMIN', 'ADMIN', 'MODERATOR', 'USUARIO', 'BANNED', name='tipoperfil'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_USUARIOS_telegram_id'), 'USUARIOS', ['telegram_id'], unique=True)
    op.create_table('CHARACTERS_H',
    sa.Column('genero', sa.Enum('HUSBANDO', 'WAIFU', name='tipocategoria'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_personagem', sa.String(), nullable=False),
    sa.Column('nome_anime', sa.String(), nullable=False),
    sa.Column('evento', sa.Enum('SEM_EVENTO', 'HALLOWEEN', 'PRIMAVERA', 'VERAO', 'INVERNO', 'OUTONO', 'ANO_NOVO', 'NATAL', 'VALENTINA', 'INFANTIL', 'COELHINHA', 'CARNAVAL', 'EMPREGADA', 'ANJO', 'ESPORTIVO', 'KIMONO', 'GALA', 'GALA_MASCULINA', 'ANO_NOVO_LUNAR', 'ENFERMEIRA', 'ESCOLAR', 'GAME', name='tipoevento'), nullable=False),
    sa.Column('raridade', sa.Enum('COMUM', 'INCOMUM', 'RARO', 'LENDARIO', 'EXCLUSIVO', 'LIMITADO', 'ESPECIAL', 'MULTIVERSO', 'ESPECTRAL', name='tiporaridade'), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('tipo_midia', sa.Enum('IMAGEM_URL', 'IMAGEM_FILEID', 'IMAGEM_BYTES', 'IMAGEM_ARQUIVO', 'IMAGEM_BASE64', 'VIDEO_BYTES', 'VIDEO_BASE64', 'VIDEO_ARQUIVO', 'VIDEO_URL', 'VIDEO_FILEID', name='tipomidia'), nullable=False),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evento'], ['E_EVENTOS.COD'], ),
    sa.ForeignKeyConstraint(['raridade'], ['E_RARIDADE.COD'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data')
    )
    op.create_index(op.f('ix_CHARACTERS_H_evento'), 'CHARACTERS_H', ['evento'], unique=False)
    op.create_index(op.f('ix_CHARACTERS_H_raridade'), 'CHARACTERS_H', ['raridade'], unique=False)
    op.create_table('CHARACTERS_W',
    sa.Column('genero', sa.Enum('HUSBANDO', 'WAIFU', name='tipocategoria'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_personagem', sa.String(), nullable=False),
    sa.Column('nome_anime', sa.String(), nullable=False),
    sa.Column('evento', sa.Enum('SEM_EVENTO', 'HALLOWEEN', 'PRIMAVERA', 'VERAO', 'INVERNO', 'OUTONO', 'ANO_NOVO', 'NATAL', 'VALENTINA', 'INFANTIL', 'COELHINHA', 'CARNAVAL', 'EMPREGADA', 'ANJO', 'ESPORTIVO', 'KIMONO', 'GALA', 'GALA_MASCULINA', 'ANO_NOVO_LUNAR', 'ENFERMEIRA', 'ESCOLAR', 'GAME', name='tipoevento'), nullable=False),
    sa.Column('raridade', sa.Enum('COMUM', 'INCOMUM', 'RARO', 'LENDARIO', 'EXCLUSIVO', 'LIMITADO', 'ESPECIAL', 'MULTIVERSO', 'ESPECTRAL', name='tiporaridade'), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('tipo_midia', sa.Enum('IMAGEM_URL', 'IMAGEM_FILEID', 'IMAGEM_BYTES', 'IMAGEM_ARQUIVO', 'IMAGEM_BASE64', 'VIDEO_BYTES', 'VIDEO_BASE64', 'VIDEO_ARQUIVO', 'VIDEO_URL', 'VIDEO_FILEID', name='tipomidia'), nullable=False),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evento'], ['E_EVENTOS.COD'], ),
    sa.ForeignKeyConstraint(['raridade'], ['E_RARIDADE.COD'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data')
    )
    op.create_index(op.f('ix_CHARACTERS_W_evento'), 'CHARACTERS_W', ['evento'], unique=False)
    op.create_index(op.f('ix_CHARACTERS_W_raridade'), 'CHARACTERS_W', ['raridade'], unique=False)
    op.create_table('COLECAO_H',
    sa.Column('ID_LOCAL', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('ID_GLOBAL', sa.Integer(), nullable=False),
    sa.Column('adicionado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ID_GLOBAL'], ['CHARACTERS_H.id'], ),
    sa.ForeignKeyConstraint(['telegram_id'], ['USUARIOS.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID_LOCAL')
    )
    op.create_index(op.f('ix_COLECAO_H_ID_GLOBAL'), 'COLECAO_H', ['ID_GLOBAL'], unique=False)
    op.create_index(op.f('ix_COLECAO_H_telegram_id'), 'COLECAO_H', ['telegram_id'], unique=False)
    op.create_table('COLECAO_W',
    sa.Column('ID_LOCAL', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('ID_GLOBAL', sa.Integer(), nullable=False),
    sa.Column('adicionado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ID_GLOBAL'], ['CHARACTERS_W.id'], ),
    sa.ForeignKeyConstraint(['telegram_id'], ['USUARIOS.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID_LOCAL')
    )
    op.create_index(op.f('ix_COLECAO_W_ID_GLOBAL'), 'COLECAO_W', ['ID_GLOBAL'], unique=False)
    op.create_index(op.f('ix_COLECAO_W_telegram_id'), 'COLECAO_W', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_COLECAO_W_telegram_id'), table_name='COLECAO_W')
    op.drop_index(op.f('ix_COLECAO_W_ID_GLOBAL'), table_name='COLECAO_W')
    op.drop_table('COLECAO_W')
    op.drop_index(op.f('ix_COLECAO_H_telegram_id'), table_name='COLECAO_H')
    op.drop_index(op.f('ix_COLECAO_H_ID_GLOBAL'), table_name='COLECAO_H')
    op.drop_table('COLECAO_H')
    op.drop_index(op.f('ix_CHARACTERS_W_raridade'), table_name='CHARACTERS_W')
    op.drop_index(op.f('ix_CHARACTERS_W_evento'), table_name='CHARACTERS_W')
    op.drop_table('CHARACTERS_W')
    op.drop_index(op.f('ix_CHARACTERS_H_raridade'), table_name='CHARACTERS_H')
    op.drop_index(op.f('ix_CHARACTERS_H_evento'), table_name='CHARACTERS_H')
    op.drop_table('CHARACTERS_H')
    op.drop_index(op.f('ix_USUARIOS_telegram_id'), table_name='USUARIOS')
    op.drop_table('USUARIOS')
    op.drop_table('E_RARIDADE')
    op.drop_table('E_EVENTOS')
    # ### end Alembic commands ###
