"""tornar_configs_opcional

Revision ID: 0bf568999c46
Revises: 4cfe81acf12f
Create Date: 2025-09-06 11:57:29.414007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0bf568999c46'
down_revision: Union[str, Sequence[str], None] = '4cfe81acf12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CHATS_TG', schema=None) as batch_op:
        batch_op.alter_column('configs',
               existing_type=sqlite.JSON(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CHATS_TG', schema=None) as batch_op:
        batch_op.alter_column('configs',
               existing_type=sqlite.JSON(),
               nullable=False)

    # ### end Alembic commands ###
