"""Corrige id_local para Identity/autoincrement

Revision ID: 3c2773b5ffc2
Revises: 0bf568999c46
Create Date: 2025-09-06 23:25:31.210086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c2773b5ffc2'
down_revision: Union[str, Sequence[str], None] = '0bf568999c46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create enum types first (with error handling for existing types)
    try:
        tipocategoria_enum = sa.Enum('HUSBANDO', 'WAIFU', name='tipocategoria')
        tipocategoria_enum.create(op.get_bind())
    except:
        pass
    
    try:
        tipoevento_enum = sa.Enum('SEM_EVENTO', 'HALLOWEEN', 'PRIMAVERA', 'VERAO', 'INVERNO', 'OUTONO', 'ANO_NOVO', 'NATAL', 'VALENTINA', 'INFANTIL', 'COELHINHA', 'CARNAVAL', 'EMPREGADA', 'ANJO', 'ESPORTIVO', 'KIMONO', 'GALA', 'GALA_MASCULINA', 'ANO_NOVO_LUNAR', 'ENFERMEIRA', 'ESCOLAR', 'GAME', name='tipoevento')
        tipoevento_enum.create(op.get_bind())
    except:
        pass
    
    try:
        tiporaridade_enum = sa.Enum('COMUM', 'INCOMUM', 'RARO', 'LENDARIO', 'EXCLUSIVO', 'LIMITADO', 'ESPECIAL', 'MULTIVERSO', 'ESPECTRAL', name='tiporaridade')
        tiporaridade_enum.create(op.get_bind())
    except:
        pass
    
    try:
        tipomidia_enum = sa.Enum('IMAGEM_URL', 'IMAGEM_FILEID', 'IMAGEM_BYTES', 'IMAGEM_ARQUIVO', 'IMAGEM_BASE64', 'VIDEO_BYTES', 'VIDEO_BASE64', 'VIDEO_ARQUIVO', 'VIDEO_URL', 'VIDEO_FILEID', name='tipomidia')
        tipomidia_enum.create(op.get_bind())
    except:
        pass
    
    try:
        tipoperfil_enum = sa.Enum('SUPREMO', 'SUPER_ADMIN', 'ADMIN', 'MODERATOR', 'USUARIO', 'BANNED', name='tipoperfil')
        tipoperfil_enum.create(op.get_bind())
    except:
        pass
    
    try:
        idioma_enum = sa.Enum('PT', 'EN', 'ES', 'FR', 'DE', 'IT', 'JA', 'KO', 'ZH', name='idioma')
        idioma_enum.create(op.get_bind())
    except:
        pass

    op.alter_column(
    "characters_h",
    "genero",
    existing_type=sa.VARCHAR(),
    type_=sa.Enum("HUSBANDO", "WAIFU", name="tipocategoria"),
    existing_nullable=False,
    postgresql_using="genero::tipocategoria",
)

    op.alter_column('characters_h', 'evento',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('SEM_EVENTO', 'HALLOWEEN', 'PRIMAVERA', 'VERAO', 'INVERNO', 'OUTONO', 'ANO_NOVO', 'NATAL', 'VALENTINA', 'INFANTIL', 'COELHINHA', 'CARNAVAL', 'EMPREGADA', 'ANJO', 'ESPORTIVO', 'KIMONO', 'GALA', 'GALA_MASCULINA', 'ANO_NOVO_LUNAR', 'ENFERMEIRA', 'ESCOLAR', 'GAME', name='tipoevento'),
               existing_nullable=False,
               postgresql_using="evento::tipoevento")
    op.alter_column('characters_h', 'raridade',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('COMUM', 'INCOMUM', 'RARO', 'LENDARIO', 'EXCLUSIVO', 'LIMITADO', 'ESPECIAL', 'MULTIVERSO', 'ESPECTRAL', name='tiporaridade'),
               existing_nullable=False,
               postgresql_using="raridade::tiporaridade")
    op.alter_column('characters_h', 'tipo_midia',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('IMAGEM_URL', 'IMAGEM_FILEID', 'IMAGEM_BYTES', 'IMAGEM_ARQUIVO', 'IMAGEM_BASE64', 'VIDEO_BYTES', 'VIDEO_BASE64', 'VIDEO_ARQUIVO', 'VIDEO_URL', 'VIDEO_FILEID', name='tipomidia'),
               existing_nullable=False,
               postgresql_using="tipo_midia::tipomidia")
    op.alter_column('characters_h', 'extras',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_characters_h_evento'), 'characters_h', ['evento'], unique=False)
    op.create_index(op.f('ix_characters_h_raridade'), 'characters_h', ['raridade'], unique=False)
    op.create_unique_constraint(None, 'characters_h', ['data'])
    op.create_foreign_key(None, 'characters_h', 'e_eventos', ['evento'], ['cod'])
    op.create_foreign_key(None, 'characters_h', 'e_raridade', ['raridade'], ['cod'])
    op.alter_column('characters_w', 'genero',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('HUSBANDO', 'WAIFU', name='tipocategoria'),
               existing_nullable=False,
               postgresql_using="genero::tipocategoria")
    op.alter_column('characters_w', 'evento',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('SEM_EVENTO', 'HALLOWEEN', 'PRIMAVERA', 'VERAO', 'INVERNO', 'OUTONO', 'ANO_NOVO', 'NATAL', 'VALENTINA', 'INFANTIL', 'COELHINHA', 'CARNAVAL', 'EMPREGADA', 'ANJO', 'ESPORTIVO', 'KIMONO', 'GALA', 'GALA_MASCULINA', 'ANO_NOVO_LUNAR', 'ENFERMEIRA', 'ESCOLAR', 'GAME', name='tipoevento'),
               existing_nullable=False,
               postgresql_using="evento::tipoevento")
    op.alter_column('characters_w', 'raridade',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('COMUM', 'INCOMUM', 'RARO', 'LENDARIO', 'EXCLUSIVO', 'LIMITADO', 'ESPECIAL', 'MULTIVERSO', 'ESPECTRAL', name='tiporaridade'),
               existing_nullable=False,
               postgresql_using="raridade::tiporaridade")
    op.alter_column('characters_w', 'tipo_midia',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('IMAGEM_URL', 'IMAGEM_FILEID', 'IMAGEM_BYTES', 'IMAGEM_ARQUIVO', 'IMAGEM_BASE64', 'VIDEO_BYTES', 'VIDEO_BASE64', 'VIDEO_ARQUIVO', 'VIDEO_URL', 'VIDEO_FILEID', name='tipomidia'),
               existing_nullable=False,
               postgresql_using="tipo_midia::tipomidia")
    op.alter_column('characters_w', 'extras',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_characters_w_evento'), 'characters_w', ['evento'], unique=False)
    op.create_index(op.f('ix_characters_w_raridade'), 'characters_w', ['raridade'], unique=False)
    op.create_unique_constraint(None, 'characters_w', ['data'])
    op.create_foreign_key(None, 'characters_w', 'e_raridade', ['raridade'], ['cod'])
    op.create_foreign_key(None, 'characters_w', 'e_eventos', ['evento'], ['cod'])
    op.alter_column('chats_tg', 'configs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('chats_tg', 'idioma',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PT', 'EN', 'ES', 'FR', 'DE', 'IT', 'JA', 'KO', 'ZH', name='idioma'),
               existing_nullable=False,
               postgresql_using="idioma::idioma")
    op.create_index(op.f('ix_chats_tg_id_grupo'), 'chats_tg', ['id_grupo'], unique=True)
    op.create_index(op.f('ix_colecao_h_id_global'), 'colecao_h', ['id_global'], unique=False)
    op.create_index(op.f('ix_colecao_h_telegram_id'), 'colecao_h', ['telegram_id'], unique=False)
    op.create_foreign_key(None, 'colecao_h', 'characters_h', ['id_global'], ['id'])
    op.create_foreign_key(None, 'colecao_h', 'usuarios', ['telegram_id'], ['telegram_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_colecao_w_id_global'), 'colecao_w', ['id_global'], unique=False)
    op.create_index(op.f('ix_colecao_w_telegram_id'), 'colecao_w', ['telegram_id'], unique=False)
    op.create_foreign_key(None, 'colecao_w', 'characters_w', ['id_global'], ['id'])
    op.create_foreign_key(None, 'colecao_w', 'usuarios', ['telegram_id'], ['telegram_id'], ondelete='CASCADE')
    op.alter_column('e_eventos', 'cod',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('SEM_EVENTO', 'HALLOWEEN', 'PRIMAVERA', 'VERAO', 'INVERNO', 'OUTONO', 'ANO_NOVO', 'NATAL', 'VALENTINA', 'INFANTIL', 'COELHINHA', 'CARNAVAL', 'EMPREGADA', 'ANJO', 'ESPORTIVO', 'KIMONO', 'GALA', 'GALA_MASCULINA', 'ANO_NOVO_LUNAR', 'ENFERMEIRA', 'ESCOLAR', 'GAME', name='tipoevento'),
               existing_nullable=False,
               postgresql_using="cod::tipoevento")
    op.create_unique_constraint(None, 'e_eventos', ['cod'])
    op.alter_column('e_raridade', 'cod',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('COMUM', 'INCOMUM', 'RARO', 'LENDARIO', 'EXCLUSIVO', 'LIMITADO', 'ESPECIAL', 'MULTIVERSO', 'ESPECTRAL', name='tiporaridade'),
               existing_nullable=False,
               postgresql_using="cod::tiporaridade")
    op.create_unique_constraint(None, 'e_raridade', ['cod'])
    op.alter_column('usuarios', 'telegram_from_user',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('usuarios', 'perfil_status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('SUPREMO', 'SUPER_ADMIN', 'ADMIN', 'MODERATOR', 'USUARIO', 'BANNED', name='tipoperfil'),
               existing_nullable=True,
               postgresql_using="perfil_status::tipoperfil")
    op.alter_column('usuarios', 'configs_w',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('usuarios', 'configs_h',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('usuarios', 'idioma_preferido',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PT', 'EN', 'ES', 'FR', 'DE', 'IT', 'JA', 'KO', 'ZH', name='idioma'),
               existing_nullable=True,
               existing_server_default=sa.text("'pt'::character varying"),
               postgresql_using="idioma_preferido::idioma")
    op.create_index(op.f('ix_usuarios_fav_h_id'), 'usuarios', ['fav_h_id'], unique=False)
    op.create_index(op.f('ix_usuarios_fav_w_id'), 'usuarios', ['fav_w_id'], unique=False)
    op.create_index(op.f('ix_usuarios_telegram_id'), 'usuarios', ['telegram_id'], unique=True)
    op.create_foreign_key(None, 'usuarios', 'characters_h', ['fav_h_id'], ['id'])
    op.create_foreign_key(None, 'usuarios', 'characters_w', ['fav_w_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_index(op.f('ix_usuarios_telegram_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_fav_w_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_fav_h_id'), table_name='usuarios')
    op.alter_column('usuarios', 'idioma_preferido',
               existing_type=sa.Enum('PT', 'EN', 'ES', 'FR', 'DE', 'IT', 'JA', 'KO', 'ZH', name='idioma'),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               existing_server_default=sa.text("'pt'::character varying"))
    op.alter_column('usuarios', 'configs_h',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('usuarios', 'configs_w',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('usuarios', 'perfil_status',
               existing_type=sa.Enum('SUPREMO', 'SUPER_ADMIN', 'ADMIN', 'MODERATOR', 'USUARIO', 'BANNED', name='tipoperfil'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('usuarios', 'telegram_from_user',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint(None, 'e_raridade', type_='unique')
    op.alter_column('e_raridade', 'cod',
               existing_type=sa.Enum('COMUM', 'INCOMUM', 'RARO', 'LENDARIO', 'EXCLUSIVO', 'LIMITADO', 'ESPECIAL', 'MULTIVERSO', 'ESPECTRAL', name='tiporaridade'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'e_eventos', type_='unique')
    op.alter_column('e_eventos', 'cod',
               existing_type=sa.Enum('SEM_EVENTO', 'HALLOWEEN', 'PRIMAVERA', 'VERAO', 'INVERNO', 'OUTONO', 'ANO_NOVO', 'NATAL', 'VALENTINA', 'INFANTIL', 'COELHINHA', 'CARNAVAL', 'EMPREGADA', 'ANJO', 'ESPORTIVO', 'KIMONO', 'GALA', 'GALA_MASCULINA', 'ANO_NOVO_LUNAR', 'ENFERMEIRA', 'ESCOLAR', 'GAME', name='tipoevento'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'colecao_w', type_='foreignkey')
    op.drop_constraint(None, 'colecao_w', type_='foreignkey')
    op.drop_index(op.f('ix_colecao_w_telegram_id'), table_name='colecao_w')
    op.drop_index(op.f('ix_colecao_w_id_global'), table_name='colecao_w')
    op.drop_constraint(None, 'colecao_h', type_='foreignkey')
    op.drop_constraint(None, 'colecao_h', type_='foreignkey')
    op.drop_index(op.f('ix_colecao_h_telegram_id'), table_name='colecao_h')
    op.drop_index(op.f('ix_colecao_h_id_global'), table_name='colecao_h')
    op.drop_index(op.f('ix_chats_tg_id_grupo'), table_name='chats_tg')
    op.alter_column('chats_tg', 'idioma',
               existing_type=sa.Enum('PT', 'EN', 'ES', 'FR', 'DE', 'IT', 'JA', 'KO', 'ZH', name='idioma'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('chats_tg', 'configs',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'characters_w', type_='foreignkey')
    op.drop_constraint(None, 'characters_w', type_='foreignkey')
    op.drop_constraint(None, 'characters_w', type_='unique')
    op.drop_index(op.f('ix_characters_w_raridade'), table_name='characters_w')
    op.drop_index(op.f('ix_characters_w_evento'), table_name='characters_w')
    op.alter_column('characters_w', 'extras',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('characters_w', 'tipo_midia',
               existing_type=sa.Enum('IMAGEM_URL', 'IMAGEM_FILEID', 'IMAGEM_BYTES', 'IMAGEM_ARQUIVO', 'IMAGEM_BASE64', 'VIDEO_BYTES', 'VIDEO_BASE64', 'VIDEO_ARQUIVO', 'VIDEO_URL', 'VIDEO_FILEID', name='tipomidia'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('characters_w', 'raridade',
               existing_type=sa.Enum('COMUM', 'INCOMUM', 'RARO', 'LENDARIO', 'EXCLUSIVO', 'LIMITADO', 'ESPECIAL', 'MULTIVERSO', 'ESPECTRAL', name='tiporaridade'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('characters_w', 'evento',
               existing_type=sa.Enum('SEM_EVENTO', 'HALLOWEEN', 'PRIMAVERA', 'VERAO', 'INVERNO', 'OUTONO', 'ANO_NOVO', 'NATAL', 'VALENTINA', 'INFANTIL', 'COELHINHA', 'CARNAVAL', 'EMPREGADA', 'ANJO', 'ESPORTIVO', 'KIMONO', 'GALA', 'GALA_MASCULINA', 'ANO_NOVO_LUNAR', 'ENFERMEIRA', 'ESCOLAR', 'GAME', name='tipoevento'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('characters_w', 'genero',
               existing_type=sa.Enum('HUSBANDO', 'WAIFU', name='tipocategoria'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'characters_h', type_='foreignkey')
    op.drop_constraint(None, 'characters_h', type_='foreignkey')
    op.drop_constraint(None, 'characters_h', type_='unique')
    op.drop_index(op.f('ix_characters_h_raridade'), table_name='characters_h')
    op.drop_index(op.f('ix_characters_h_evento'), table_name='characters_h')
    op.alter_column('characters_h', 'extras',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('characters_h', 'tipo_midia',
               existing_type=sa.Enum('IMAGEM_URL', 'IMAGEM_FILEID', 'IMAGEM_BYTES', 'IMAGEM_ARQUIVO', 'IMAGEM_BASE64', 'VIDEO_BYTES', 'VIDEO_BASE64', 'VIDEO_ARQUIVO', 'VIDEO_URL', 'VIDEO_FILEID', name='tipomidia'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('characters_h', 'raridade',
               existing_type=sa.Enum('COMUM', 'INCOMUM', 'RARO', 'LENDARIO', 'EXCLUSIVO', 'LIMITADO', 'ESPECIAL', 'MULTIVERSO', 'ESPECTRAL', name='tiporaridade'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('characters_h', 'evento',
               existing_type=sa.Enum('SEM_EVENTO', 'HALLOWEEN', 'PRIMAVERA', 'VERAO', 'INVERNO', 'OUTONO', 'ANO_NOVO', 'NATAL', 'VALENTINA', 'INFANTIL', 'COELHINHA', 'CARNAVAL', 'EMPREGADA', 'ANJO', 'ESPORTIVO', 'KIMONO', 'GALA', 'GALA_MASCULINA', 'ANO_NOVO_LUNAR', 'ENFERMEIRA', 'ESCOLAR', 'GAME', name='tipoevento'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('characters_h', 'genero',
               existing_type=sa.Enum('HUSBANDO', 'WAIFU', name='tipocategoria'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    
    # Drop enum types
    try:
        sa.Enum(name='tipoperfil').drop(op.get_bind())
    except:
        pass
    try:
        sa.Enum(name='tipomidia').drop(op.get_bind())
    except:
        pass
    try:
        sa.Enum(name='tiporaridade').drop(op.get_bind())
    except:
        pass
    try:
        sa.Enum(name='tipoevento').drop(op.get_bind())
    except:
        pass
    try:
        sa.Enum(name='tipocategoria').drop(op.get_bind())
    except:
        pass
    # ### end Alembic commands ###
