"""Criando tabela GROUPS_TG

Revision ID: 46634fbac903
Revises: 53903f6f0d99
Create Date: 2025-09-04 19:45:10.070913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46634fbac903'
down_revision: Union[str, Sequence[str], None] = '53903f6f0d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USUARIOS') as batch_op:
        batch_op.create_foreign_key('fk_usuarios_fav_h_id', 'CHARACTERS_H', ['fav_h_id'], ['id'])
        batch_op.create_foreign_key('fk_usuarios_fav_w_id', 'CHARACTERS_W', ['fav_w_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USUARIOS') as batch_op:
        batch_op.drop_constraint('fk_usuarios_fav_h_id', type_='foreignkey')
        batch_op.drop_constraint('fk_usuarios_fav_w_id', type_='foreignkey')
    # ### end Alembic commands ###
