"""adicionar_campo_idioma_chats_tg

Revision ID: 4cfe81acf12f
Revises: cc216759daba
Create Date: 2025-09-06 11:52:39.958443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '4cfe81acf12f'
down_revision: Union[str, Sequence[str], None] = 'cc216759daba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_USUARIOS')
    op.drop_table('_alembic_tmp_GRUPOS_IDIOMAS')
    op.drop_table('GRUPOS_IDIOMAS')
    with op.batch_alter_table('CHATS_TG', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idioma', sa.Enum('PT', 'EN', 'ES', 'FR', 'DE', 'IT', 'JA', 'KO', 'ZH', name='idioma'), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CHATS_TG', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('idioma')

    op.create_table('GRUPOS_IDIOMAS',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.Column('idioma', sa.VARCHAR(length=2), server_default=sa.text("'pt'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_table('_alembic_tmp_GRUPOS_IDIOMAS',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chat_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('idioma_w', sa.VARCHAR(length=2), nullable=False),
    sa.Column('idioma_h', sa.VARCHAR(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_table('_alembic_tmp_USUARIOS',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('telegram_id', sa.INTEGER(), nullable=False),
    sa.Column('telegram_from_user', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('perfil_status', sa.VARCHAR(length=11), nullable=True),
    sa.Column('fav_w_id', sa.INTEGER(), nullable=True),
    sa.Column('fav_h_id', sa.INTEGER(), nullable=True),
    sa.Column('Configs_w', sqlite.JSON(), nullable=True),
    sa.Column('Configs_h', sqlite.JSON(), nullable=True),
    sa.Column('idioma_preferido', sa.VARCHAR(length=2), server_default=sa.text("'pt'"), nullable=True),
    sa.ForeignKeyConstraint(['fav_h_id'], ['CHARACTERS_H.id'], name=op.f('fk_usuarios_fav_h_id')),
    sa.ForeignKeyConstraint(['fav_w_id'], ['CHARACTERS_W.id'], name=op.f('fk_usuarios_fav_w_id')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
