"""update_tipo_evento_enum

Revision ID: 746b3e8d9014
Revises: 8d7faf9d6785
Create Date: 2025-09-12 23:50:38.258257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '746b3e8d9014'
down_revision: Union[str, Sequence[str], None] = '8d7faf9d6785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters_h', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_characters_h_evento'), 'characters_h', ['evento'], unique=False)
    op.create_index(op.f('ix_characters_h_raridade'), 'characters_h', ['raridade'], unique=False)
    op.create_unique_constraint(None, 'characters_h', ['data'])
    op.create_foreign_key(None, 'characters_h', 'e_raridade', ['raridade'], ['cod'])
    op.create_foreign_key(None, 'characters_h', 'e_eventos', ['evento'], ['cod'])
    op.alter_column('characters_w', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_characters_w_evento'), 'characters_w', ['evento'], unique=False)
    op.create_index(op.f('ix_characters_w_raridade'), 'characters_w', ['raridade'], unique=False)
    op.create_unique_constraint(None, 'characters_w', ['data'])
    op.create_foreign_key(None, 'characters_w', 'e_raridade', ['raridade'], ['cod'])
    op.create_foreign_key(None, 'characters_w', 'e_eventos', ['evento'], ['cod'])
    op.alter_column('chats_tg', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_chats_tg_id_grupo'), 'chats_tg', ['id_grupo'], unique=True)
    op.alter_column('colecao_h', 'id_local',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_colecao_h_id_global'), 'colecao_h', ['id_global'], unique=False)
    op.create_index(op.f('ix_colecao_h_telegram_id'), 'colecao_h', ['telegram_id'], unique=False)
    op.create_foreign_key(None, 'colecao_h', 'usuarios', ['telegram_id'], ['telegram_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'colecao_h', 'characters_h', ['id_global'], ['id'])
    op.alter_column('colecao_w', 'id_local',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_colecao_w_id_global'), 'colecao_w', ['id_global'], unique=False)
    op.create_index(op.f('ix_colecao_w_telegram_id'), 'colecao_w', ['telegram_id'], unique=False)
    op.create_foreign_key(None, 'colecao_w', 'characters_w', ['id_global'], ['id'])
    op.create_foreign_key(None, 'colecao_w', 'usuarios', ['telegram_id'], ['telegram_id'], ondelete='CASCADE')
    op.alter_column('e_eventos', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('e_raridade', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('usuarios', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_usuarios_fav_h_id'), 'usuarios', ['fav_h_id'], unique=False)
    op.create_index(op.f('ix_usuarios_fav_w_id'), 'usuarios', ['fav_w_id'], unique=False)
    op.create_index(op.f('ix_usuarios_telegram_id'), 'usuarios', ['telegram_id'], unique=True)
    op.create_foreign_key(None, 'usuarios', 'characters_w', ['fav_w_id'], ['id'])
    op.create_foreign_key(None, 'usuarios', 'characters_h', ['fav_h_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_index(op.f('ix_usuarios_telegram_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_fav_w_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_fav_h_id'), table_name='usuarios')
    op.alter_column('usuarios', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('e_raridade', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('e_eventos', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'colecao_w', type_='foreignkey')
    op.drop_constraint(None, 'colecao_w', type_='foreignkey')
    op.drop_index(op.f('ix_colecao_w_telegram_id'), table_name='colecao_w')
    op.drop_index(op.f('ix_colecao_w_id_global'), table_name='colecao_w')
    op.alter_column('colecao_w', 'id_local',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'colecao_h', type_='foreignkey')
    op.drop_constraint(None, 'colecao_h', type_='foreignkey')
    op.drop_index(op.f('ix_colecao_h_telegram_id'), table_name='colecao_h')
    op.drop_index(op.f('ix_colecao_h_id_global'), table_name='colecao_h')
    op.alter_column('colecao_h', 'id_local',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_chats_tg_id_grupo'), table_name='chats_tg')
    op.alter_column('chats_tg', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'characters_w', type_='foreignkey')
    op.drop_constraint(None, 'characters_w', type_='foreignkey')
    op.drop_constraint(None, 'characters_w', type_='unique')
    op.drop_index(op.f('ix_characters_w_raridade'), table_name='characters_w')
    op.drop_index(op.f('ix_characters_w_evento'), table_name='characters_w')
    op.alter_column('characters_w', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'characters_h', type_='foreignkey')
    op.drop_constraint(None, 'characters_h', type_='foreignkey')
    op.drop_constraint(None, 'characters_h', type_='unique')
    op.drop_index(op.f('ix_characters_h_raridade'), table_name='characters_h')
    op.drop_index(op.f('ix_characters_h_evento'), table_name='characters_h')
    op.alter_column('characters_h', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
