"""alteração na base charecter

Revision ID: 2a33162e98e0
Revises: ba5addb25f91
Create Date: 2026-01-04 13:17:38.675449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a33162e98e0'
down_revision: Union[str, Sequence[str], None] = 'ba5addb25f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters_husbando', sa.Column('origem', sa.String(length=100), nullable=False))
    op.add_column('characters_husbando', sa.Column('tipo_fonte', sa.String(length=500), nullable=False))
    op.add_column('characters_husbando', sa.Column('data', sa.String(), nullable=False))
    op.drop_constraint(op.f('characters_husbando_date_added_key'), 'characters_husbando', type_='unique')
    op.create_unique_constraint(None, 'characters_husbando', ['data'])
    op.drop_column('characters_husbando', 'original')
    op.drop_column('characters_husbando', 'character_image_url')
    op.drop_column('characters_husbando', 'date_added')
    op.add_column('characters_waifu', sa.Column('origem', sa.String(length=100), nullable=False))
    op.add_column('characters_waifu', sa.Column('tipo_fonte', sa.String(length=500), nullable=False))
    op.add_column('characters_waifu', sa.Column('data', sa.String(), nullable=False))
    op.drop_constraint(op.f('characters_waifu_date_added_key'), 'characters_waifu', type_='unique')
    op.create_unique_constraint(None, 'characters_waifu', ['data'])
    op.drop_column('characters_waifu', 'original')
    op.drop_column('characters_waifu', 'character_image_url')
    op.drop_column('characters_waifu', 'date_added')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters_waifu', sa.Column('date_added', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('characters_waifu', sa.Column('character_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('characters_waifu', sa.Column('original', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'characters_waifu', type_='unique')
    op.create_unique_constraint(op.f('characters_waifu_date_added_key'), 'characters_waifu', ['date_added'], postgresql_nulls_not_distinct=False)
    op.drop_column('characters_waifu', 'data')
    op.drop_column('characters_waifu', 'tipo_fonte')
    op.drop_column('characters_waifu', 'origem')
    op.add_column('characters_husbando', sa.Column('date_added', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('characters_husbando', sa.Column('character_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('characters_husbando', sa.Column('original', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'characters_husbando', type_='unique')
    op.create_unique_constraint(op.f('characters_husbando_date_added_key'), 'characters_husbando', ['date_added'], postgresql_nulls_not_distinct=False)
    op.drop_column('characters_husbando', 'data')
    op.drop_column('characters_husbando', 'tipo_fonte')
    op.drop_column('characters_husbando', 'origem')
    # ### end Alembic commands ###
