"""create users table

Revision ID: 59f6deead8aa
Revises: 
Create Date: 2026-01-04 09:27:32.450897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59f6deead8aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Enum('NONE', 'HALLOWEEN', 'SPRING', 'SUMMER', 'WINTER', 'AUTUMN', 'NEW_YEAR', 'CHRISTMAS', 'VALENTINE', 'CHILDREN', 'BUNNY', 'CARNIVAL', 'MAID', 'ANGEL', 'SPORTS', 'KIMONO', 'GALA', 'GALA_MASCULINA', 'NEW_YEAR_LUNAR', 'NURSE', 'SCHOOL', 'GAME', name='eventtype'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('emoji', sa.String(length=5), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_code'), 'events', ['code'], unique=True)
    op.create_table('rarities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Enum('COMMON', 'UNCOMMON', 'RARE', 'LEGENDARY', 'EXCLUSIVE', 'LIMITED', 'SPECIAL', 'MULTIVERSE', 'SPECTRAL', name='raritytype'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('emoji', sa.String(length=5), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rarities_code'), 'rarities', ['code'], unique=True)
    op.create_table('telegram_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('language', sa.Enum('PT', 'EN', 'ES', 'FR', 'DE', 'IT', 'JA', 'KO', 'ZH', name='language'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_groups_group_id'), 'telegram_groups', ['group_id'], unique=True)
    op.create_table('characters_husbando',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=False),
    sa.Column('anime_name', sa.String(length=100), nullable=False),
    sa.Column('event_code', sa.Enum('NONE', 'HALLOWEEN', 'SPRING', 'SUMMER', 'WINTER', 'AUTUMN', 'NEW_YEAR', 'CHRISTMAS', 'VALENTINE', 'CHILDREN', 'BUNNY', 'CARNIVAL', 'MAID', 'ANGEL', 'SPORTS', 'KIMONO', 'GALA', 'GALA_MASCULINA', 'NEW_YEAR_LUNAR', 'NURSE', 'SCHOOL', 'GAME', name='eventtype'), nullable=False),
    sa.Column('rarity_code', sa.Enum('COMMON', 'UNCOMMON', 'RARE', 'LEGENDARY', 'EXCLUSIVE', 'LIMITED', 'SPECIAL', 'MULTIVERSE', 'SPECTRAL', name='raritytype'), nullable=False),
    sa.Column('date_added', sa.String(), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE_URL', 'IMAGE_FILEID', 'IMAGE_BYTES', 'IMAGE_FILE', 'IMAGE_BASE64', 'VIDEO_BYTES', 'VIDEO_BASE64', 'VIDEO_FILE', 'VIDEO_URL', 'VIDEO_FILEID', name='mediatype'), nullable=False),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_code'], ['events.code'], ),
    sa.ForeignKeyConstraint(['rarity_code'], ['rarities.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_added')
    )
    op.create_index(op.f('ix_characters_husbando_event_code'), 'characters_husbando', ['event_code'], unique=False)
    op.create_index(op.f('ix_characters_husbando_rarity_code'), 'characters_husbando', ['rarity_code'], unique=False)
    op.create_table('characters_waifu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=False),
    sa.Column('anime_name', sa.String(length=100), nullable=False),
    sa.Column('event_code', sa.Enum('NONE', 'HALLOWEEN', 'SPRING', 'SUMMER', 'WINTER', 'AUTUMN', 'NEW_YEAR', 'CHRISTMAS', 'VALENTINE', 'CHILDREN', 'BUNNY', 'CARNIVAL', 'MAID', 'ANGEL', 'SPORTS', 'KIMONO', 'GALA', 'GALA_MASCULINA', 'NEW_YEAR_LUNAR', 'NURSE', 'SCHOOL', 'GAME', name='eventtype'), nullable=False),
    sa.Column('rarity_code', sa.Enum('COMMON', 'UNCOMMON', 'RARE', 'LEGENDARY', 'EXCLUSIVE', 'LIMITED', 'SPECIAL', 'MULTIVERSE', 'SPECTRAL', name='raritytype'), nullable=False),
    sa.Column('date_added', sa.String(), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE_URL', 'IMAGE_FILEID', 'IMAGE_BYTES', 'IMAGE_FILE', 'IMAGE_BASE64', 'VIDEO_BYTES', 'VIDEO_BASE64', 'VIDEO_FILE', 'VIDEO_URL', 'VIDEO_FILEID', name='mediatype'), nullable=False),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_code'], ['events.code'], ),
    sa.ForeignKeyConstraint(['rarity_code'], ['rarities.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_added')
    )
    op.create_index(op.f('ix_characters_waifu_event_code'), 'characters_waifu', ['event_code'], unique=False)
    op.create_index(op.f('ix_characters_waifu_rarity_code'), 'characters_waifu', ['rarity_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_user_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('favorite_waifu_id', sa.Integer(), nullable=True),
    sa.Column('favorite_husbando_id', sa.Integer(), nullable=True),
    sa.Column('profile_status', sa.Enum('SUPREME', 'SUPER_ADMIN', 'ADMIN', 'MODERATOR', 'USER', 'BANNED', name='profiletype'), nullable=True),
    sa.Column('waifu_config', sa.JSON(), nullable=False),
    sa.Column('husbando_config', sa.JSON(), nullable=False),
    sa.Column('preferred_language', sa.Enum('PT', 'EN', 'ES', 'FR', 'DE', 'IT', 'JA', 'KO', 'ZH', name='language'), nullable=False),
    sa.ForeignKeyConstraint(['favorite_husbando_id'], ['characters_husbando.id'], ),
    sa.ForeignKeyConstraint(['favorite_waifu_id'], ['characters_waifu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_favorite_husbando_id'), 'users', ['favorite_husbando_id'], unique=False)
    op.create_index(op.f('ix_users_favorite_waifu_id'), 'users', ['favorite_waifu_id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('husbando_collection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters_husbando.id'], ),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_husbando_collection_character_id'), 'husbando_collection', ['character_id'], unique=False)
    op.create_index(op.f('ix_husbando_collection_telegram_id'), 'husbando_collection', ['telegram_id'], unique=False)
    op.create_table('waifu_collection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters_waifu.id'], ),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waifu_collection_character_id'), 'waifu_collection', ['character_id'], unique=False)
    op.create_index(op.f('ix_waifu_collection_telegram_id'), 'waifu_collection', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waifu_collection_telegram_id'), table_name='waifu_collection')
    op.drop_index(op.f('ix_waifu_collection_character_id'), table_name='waifu_collection')
    op.drop_table('waifu_collection')
    op.drop_index(op.f('ix_husbando_collection_telegram_id'), table_name='husbando_collection')
    op.drop_index(op.f('ix_husbando_collection_character_id'), table_name='husbando_collection')
    op.drop_table('husbando_collection')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_favorite_waifu_id'), table_name='users')
    op.drop_index(op.f('ix_users_favorite_husbando_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_characters_waifu_rarity_code'), table_name='characters_waifu')
    op.drop_index(op.f('ix_characters_waifu_event_code'), table_name='characters_waifu')
    op.drop_table('characters_waifu')
    op.drop_index(op.f('ix_characters_husbando_rarity_code'), table_name='characters_husbando')
    op.drop_index(op.f('ix_characters_husbando_event_code'), table_name='characters_husbando')
    op.drop_table('characters_husbando')
    op.drop_index(op.f('ix_telegram_groups_group_id'), table_name='telegram_groups')
    op.drop_table('telegram_groups')
    op.drop_index(op.f('ix_rarities_code'), table_name='rarities')
    op.drop_table('rarities')
    op.drop_index(op.f('ix_events_code'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
