"""alteração na base charecter

Revision ID: ba5addb25f91
Revises: 59f6deead8aa
Create Date: 2026-01-04 13:12:40.402335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba5addb25f91'
down_revision: Union[str, Sequence[str], None] = '59f6deead8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters_husbando', sa.Column('original', sa.String(length=100), nullable=False))
    op.add_column('characters_husbando', sa.Column('character_image_url', sa.String(length=500), nullable=False))
    op.drop_column('characters_husbando', 'anime_name')
    op.add_column('characters_waifu', sa.Column('original', sa.String(length=100), nullable=False))
    op.add_column('characters_waifu', sa.Column('character_image_url', sa.String(length=500), nullable=False))
    op.drop_column('characters_waifu', 'anime_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters_waifu', sa.Column('anime_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('characters_waifu', 'character_image_url')
    op.drop_column('characters_waifu', 'original')
    op.add_column('characters_husbando', sa.Column('anime_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('characters_husbando', 'character_image_url')
    op.drop_column('characters_husbando', 'original')
    # ### end Alembic commands ###
