# Estágio 1: Instalação de dependências
FROM node:22-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/
# Instalamos tudo (incluindo devDeps) para poder buildar
RUN npm ci

# Estágio 2: Build
FROM node:22-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Gera o Prisma Client e builda o Next.js
RUN npx prisma generate
RUN npm run build

# Estágio 3: Runner (Imagem Final Ultra Leve)
FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copiamos apenas o necessário do standalone
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

# O Prisma precisa do engine binário para rodar
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma

USER nextjs
EXPOSE 3000
ENV PORT=3000

# No modo standalone, o Next gera um server.js próprio, dispensando o npm start
CMD ["node", "server.js"]