# Estágio 1: Dependências
FROM node:22-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/
# Instalamos tudo para o build
RUN npm ci

# Estágio 2: Build
FROM node:22-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Gerar Prisma Client e fazer o Build do Next.js
RUN npx prisma generate
RUN npm run build

# Estágio 3: Runner (Imagem Final)
FROM node:22-alpine AS runner
RUN apk update && apk upgrade

WORKDIR /app

ENV NODE_ENV=production

# Criar um usuário de sistema para segurança
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copiamos apenas o essencial do estágio de build
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

USER nextjs

EXPOSE 3000

CMD ["npm", "run", "start"]


